scrape_configs:
  - job_name: "minimarket-backend"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8080"]
        labels:
          application: "minimarket-backend"
